### PR TITLE
Improve OID type

### PR DESCRIPTION
**Pull request by jethrogb**
Changing the `Display` impl for OID may or may not be a breaking change, depending on your point of view.

cc @aandyl

### CODE REVIEW

**Review by est31 — CHANGES_REQUESTED** [review]
Looks great overall, but this bumps the minimum required Rust version to 1.17 I think. Could you please edit .travis.yml and README to account for 1.17.0?

**Comment by jethrogb** [comment]
Sure, or I can just change it so older Rust is still supported, what do you prefer?

**Comment by est31** [comment]
I guess changing it would avoid having to make a semver breaking release. So that's slightly preferable. If there is a language change that gives us more than this little sugar, we can still increase the MSRV.

**Comment by jethrogb** [comment]
CI passes now :)

**Review by est31 — APPROVED** [review]

**Pull request merged**
